### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by miladfa7** [practical-recommender-systems/moviegeek#20]
**python3 -m builder.lda_model_calculator**

/usr/local/lib/python3.6/dist-packages/past/translation/__init__.py:35: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/local/lib/python3.6/dist-packages/scipy/sparse/sparsetools.py:21: DeprecationWarning: `scipy.sparse.sparsetools` is deprecated!
scipy.sparse.sparsetools is a private module for scipy.sparse, and should not be used.
  _deprecated()
Calculating lda model...
No descriptions were found, run populate_sample_of_descriptions
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/milad/Desktop/moviegeek/builder/lda_model_calculator.py", line 245, in **[module]**
    lda.train(data, docs)
  File "/home/milad/Desktop/moviegeek/builder/lda_model_calculator.py", line 82, in train
    self.build_lda_model(data, docs, NUM_TOPICS)
  File "/home/milad/Desktop/moviegeek/builder/lda_model_calculator.py", line 94, in build_lda_model
    for d in tqdm(data):

TypeError: 'module' object is not callable

**Please help me**

**Comment by miladfa7** [comment]
Please help me

**Comment by kimfalk** [comment]
Did you try to follow the message? 

> No descriptions were found, run populate_sample_of_descriptions
