### ISSUE TITLE
no such table: main.moviegeeks_movie__old

### ISSUE THREAD

**Issue by mul53** [practical-recommender-systems/moviegeek#26]
I encountered this error when running `python3 populate_moviegeek.py`, even though i ran these commands.
```
> python3 manage.py makemigrations
> python3 manage.py migrate
``` 
Starting MovieGeeks Population script...
truncate db
finished truncate db
movie data downloaded
  0%|                                               | 0/34213 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: main.moviegeeks_movie__old

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "populate_moviegeek.py", line 63, in <module>
    populate()
  File "populate_moviegeek.py", line 57, in populate
    create_movie(m[0], m[1], m[2])
  File "populate_moviegeek.py", line 25, in create_movie
    movie.genres.add(g)
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 926, in add
    self._add_items(self.source_field_name, self.target_field_name, *objs)
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 1093, in _add_items
    for obj_id in new_ids
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/models/query.py", line 465, in bulk_create
    ids = self._batched_insert(objs_without_pk, fields, batch_size)
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/models/query.py", line 1155, in _batched_insert
    self._insert(item, fields=fields, using=self.db)
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mulenga/projects/moviegeek/prs/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: main.moviegeeks_movie__old

**Comment by pfaraee** [comment]
Same Issue.
On MacOS 10.14.6
Ran this as well: /Applications/Python\ 3.6/Install\ Certificates.command, no luck.

**Comment by chen-bowen** [comment]
I googled how to create `Certificates.command ` and found another solution. https://timonweb.com/tutorials/fixing-certificate_verify_failed-error-when-trying-requests_html-out-on-mac/ 

you could try `pip install --upgrade certifi`
