### ISSUE TITLE
I cannot migrate  [ not found ./lda/corpus.mm]

### ISSUE THREAD

**Issue by pigooosuke** [practical-recommender-systems/moviegeek#4]
I tried these setup code.
```
git clone https://github.com/practical-recommender-systems/moviegeek.git
pip install -r requirements.txt
pip install psycopg2
vi prs_project/settings.py
```

But, It returned that corpus are not found. Is any solution?
And, When I comment out  "recommender.urls PATH" in  prs_projects/urls.py
I succeeded in migrations.

```
root@31f695783e4f:~/moviegeek# python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/root/moviegeek/prs_project/urls.py", line 12, in <module>
    url(r'^rec/', include('recommender.urls'))
  File "/usr/local/lib/python3.6/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/root/moviegeek/recommender/urls.py", line 2, in <module>
    from recommender import views
  File "/root/moviegeek/recommender/views.py", line 19, in <module>
    from recs.content_based_recommender import ContentBasedRecs
  File "/root/moviegeek/recs/content_based_recommender.py", line 14, in <module>
    class ContentBasedRecs(base_recommender):
  File "/root/moviegeek/recs/content_based_recommender.py", line 17, in ContentBasedRecs
    corpus=corpora.MmCorpus(lda_path + 'corpus.mm'),
  File "/usr/local/lib/python3.6/site-packages/gensim/corpora/mmcorpus.py", line 29, in __init__
    matutils.MmReader.__init__(self, fname)
  File "/usr/local/lib/python3.6/site-packages/gensim/matutils.py", line 741, in __init__
    with utils.file_or_filename(self.input) as lines:
  File "/usr/local/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/gensim/utils.py", line 140, in file_or_filename
    yield smart_open(input)
  File "/usr/local/lib/python3.6/site-packages/smart_open/smart_open_lib.py", line 138, in smart_open
    return file_smart_open(parsed_uri.uri_path, mode)
  File "/usr/local/lib/python3.6/site-packages/smart_open/smart_open_lib.py", line 642, in file_smart_open
    return compression_wrapper(open(fname, mode), fname, mode)
FileNotFoundError: [Errno 2] No such file or directory: './lda/corpus.mm'
```

**Comment by kimfalk** [comment]
Hi, 

Sorry for the late reply and thank you for trying out my site. 

The issue with the copus file missing is fixed now.
