### ISSUE TITLE
there was a error when i access the page.

### ISSUE THREAD

**Issue by isaacyang608** [practical-recommender-systems/moviegeek#54]
stated the program..
```bash
(base) E:\毕业设计\参考系统\moviegeek-master>python ./manage.py runserver 127.0.0.1:8081
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
analytics.Cluster: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AnalyticsConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.mod
els.BigAutoField'.
analytics.Rating: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AnalyticsConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.mod
els.BigAutoField'.
collector.Log: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the CollectorConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.mod
els.BigAutoField'.
moviegeeks.Genre: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the MoviegeeksConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.mo
dels.BigAutoField'.
recommender.LdaSimilarity: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the RecommenderConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.m
odels.BigAutoField'.
recommender.MovieDescriptions: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the RecommenderConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.m
odels.BigAutoField'.
recommender.Recs: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the RecommenderConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.m
odels.BigAutoField'.
recommender.SeededRecs: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the RecommenderConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.m
odels.BigAutoField'.
recommender.Similarity: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the RecommenderConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.m
odels.BigAutoField'.

System check identified 9 issues (0 silenced).
February 22, 2022 - 21:27:14
Django version 3.2.12, using settings 'prs_project.settings'
Starting development server at http://127.0.0.1:8081/
Quit the server with CTRL-BREAK.
```
and when i try to acess the index,the error jumped...
```bash
Internal Server Error: /movies/
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "E:\毕业设计\参考系统\moviegeek-master\moviegeeks\views.py", line 14, in index
    api_key = get_api_key()
  File "E:\毕业设计\参考系统\moviegeek-master\moviegeeks\views.py", line 140, in get_api_key
    cred = json.loads(open(".prs").read())
FileNotFoundError: [Errno 2] No such file or directory: '.prs'
[22/Feb/2022 21:30:11] "GET /movies/ HTTP/1.1" 500 74417
```

**Comment by isaacyang608** [comment]
Appreciate if you can help. Thanks.

**Comment by kimfalk** [comment]
You have to create the `.prs` file as the READ.ME explains.
